#! /usr/bin/env fish

if contains -- "--build" $argv
  yarn build --release
end

cp build/static/js/main.*.js forjira/main.js
cp build/static/css/main.*.css forjira/main.css

if contains -- "--push" $argv
    echo "pusing to git"
    git add .
    git commit -m "push new build"
    git push
else
    echo ""
    echo "NOTE: you must commit and push these changes to see them in jira"
end
